version: '3.8'

services:
  postgres:
    image: 'postgres:16'
    environment:
      POSTGRES_DB: runnersdb
      POSTGRES_USER: kristjan
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'